# Generated by Django 5.2.9 on 2026-02-16 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GOLD_GRAM', 'Gram Altın'), ('GOLD_QUARTER', 'Çeyrek Altın'), ('GOLD_HALF', 'Yarım Altın'), ('GOLD_FULL', 'Tam Altın'), ('CRYPTO_BTC', 'Bitcoin'), ('CRYPTO_ETH', 'Ethereum'), ('CRYPTO_SOL', 'Solana'), ('CURRENCY_USD', 'Dolar'), ('CURRENCY_EUR', 'Euro'), ('STOCK', 'Hisse Senedi'), ('SILVER_GRAM', 'Gram Gümüş')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Alış'), ('SELL', 'Satış')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.asset')),
            ],
        ),
    ]
