# Generated by Django 5.2.11 on 2026-02-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('GOLD_GRAM', 'Gram Altın'), ('GOLD_QUARTER', 'Çeyrek Altın'), ('GOLD_HALF', 'Yarım Altın'), ('GOLD_FULL', 'Tam Altın'), ('SILVER_GRAM', 'Gram Gümüş'), ('PLATINUM_GRAM', 'Gram Platin'), ('PALLADIUM_GRAM', 'Gram Paladyum'), ('CRYPTO_BTC', 'Bitcoin'), ('CRYPTO_ETH', 'Ethereum'), ('CRYPTO_SOL', 'Solana'), ('CRYPTO_BNB', 'Binance Coin'), ('CRYPTO_XRP', 'Ripple'), ('CURRENCY_USD', 'Dolar'), ('CURRENCY_EUR', 'Euro'), ('CURRENCY_GBP', 'Sterlin'), ('CURRENCY_JPY', 'Japon Yeni'), ('CURRENCY_CHF', 'İsviçre Frangı'), ('STOCK', 'Hisse Senedi')], max_length=20),
        ),
    ]
