# Generated by Django 5.2.11 on 2026-03-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
