# Generated by Django 5.2.11 on 2026-02-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='market_type',
            field=models.CharField(choices=[('commodity', 'Emtia'), ('stock', 'Borsa'), ('currency', 'Döviz'), ('crypto', 'Kripto')], default='stock', max_length=20),
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('market_type', models.CharField(max_length=20)),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('condition', models.CharField(choices=[('>', 'Büyüktür'), ('<', 'Küçüktür')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
