# Generated by Django 5.2.11 on 2026-02-18 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketdata_category_marketdata_market_type_alarm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='market_type',
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='category',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='condition',
            field=models.CharField(choices=[('>', 'Büyüktür'), ('<', 'Küçüktür')], max_length=1),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='target_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_alarms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='market_type',
            field=models.CharField(choices=[('commodity', 'Emtia'), ('stock', 'Borsa'), ('currency', 'Döviz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
