# Generated by Django 5.2.11 on 2026-02-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_alarm_market_type_remove_marketdata_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='price_change_24h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
