# Generated by Django 5.2.11 on 2026-02-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_marketdata_price_change_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='day_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='day_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='symbol',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
