# Generated by Django 5.2.11 on 2026-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_marketdata_day_high_marketdata_day_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='is_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='parent_symbol',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
