# Generated by Django 5.2.11 on 2026-02-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
